def reset(text): return f"\033[0m{text}\033[0m".lstrip()
def bold(text): return f"\033[1m{text}\033[0m".lstrip()
def fade(text): return f"\033[2m{text}\033[0m".lstrip()
def italic(text): return f"\033[3m{text}\033[0m".lstrip()
def underline(text): return f"\033[4m{text}\033[0m".lstrip()
def blink_slow(text): return f"\033[5m{text}\033[0m".lstrip()
def blink_fast(text): return f"\033[6m{text}\033[0m".lstrip()
def reverse(text): return f"\033[7m{text}\033[0m".lstrip()
def hidden(text): return f"\033[8m{text}\033[0m".lstrip()
def concealed(text): return f"\033[9m{text}\033[0m".lstrip()
def blink_off(text): return f"\033[25m{text}\033[0m".lstrip()
def conceal_off(text): return f"\033[28m{text}\033[0m".lstrip()

def black(text): return f"\033[30m{text}\033[0m".lstrip()
def red(text): return f"\033[31m{text}\033[0m".lstrip()
def green(text): return f"\033[32m{text}\033[0m".lstrip()
def yellow(text): return f"\033[33m{text}\033[0m".lstrip()
def blue(text): return f"\033[34m{text}\033[0m".lstrip()
def magenta(text): return f"\033[35m{text}\033[0m".lstrip()
def cyan(text): return f"\033[36m{text}\033[0m".lstrip()
def white(text): return f"\033[37m{text}\033[0m".lstrip()
def gray(text): return f"\033[90m{text}\033[0m".lstrip()

def orange(text): return f"\x1b[38;5;208m{text}\x1b[0m".lstrip()
def purple(text): return f"\x1b[38;5;129m{text}\x1b[0m".lstrip()

def demo():
    print(f"This is {bold('bold')} text.")
    print(f"This is {fade('faded')} text.")
    print(f"This is {italic('italic')} text.")
    print(f"This is {underline('underlined')} text.")
    print(f"This is {blink_slow('slowly blinking')} text.")
    print(f"This is {blink_fast('fast blinking')} text.")
    print(f"This is {reverse('reversed')} text.")
    print(f"This is {hidden('hidden')} text.")
    print(f"This is {concealed('concealed')} text.")
    print(f"This is {blink_off('no longer blinking')} text.")
    print(f"This is {conceal_off('no longer concealed')} text.")

    print(f"This is {black('black')} text.")
    print(f"This is {red('red')} text.")
    print(f"This is {green('green')} text.")
    print(f"This is {yellow('yellow')} text.")
    print(f"This is {blue('blue')} text.")
    print(f"This is {magenta('magenta')} text.")
    print(f"This is {cyan('cyan')} text.")
    print(f"This is {white('white')} text.")
    print(f"This is {gray('gray')} text.")
    print(f"This is {orange('orange')} text.")
    print(f"This is {purple('purple')} text.")